### ISSUE TITLE
ICE's

### ISSUE THREAD

**Issue by Zopolis4** [Zopolis4/gcj#2] opened 2022-06-17 01:59 UTC
A $50 USD [bounty](https://app.bountysource.com/issues/109355626-ice-s) has been assigned to this issue.

Currently, on the `mstermerge` branch, compilation will fail on the following error:
```
libtool: compile:  /home/zopolis4/burngnu/./gcc/xgcc -shared-libgcc -B/home/zopolis4/burngnu/./gcc -nostdinc++ -L/home/zopolis4/burngnu/x86_64-pc-linux-gnu/32/libstdc++-v3/src -L/home/zopolis4/burngnu/x86_64-pc-linux-gnu/32/libstdc++-v3/src/.libs -L/home/zopolis4/burngnu/x86_64-pc-linux-gnu/32/libstdc++-v3/libsupc++/.libs -B/usr/local/x86_64-pc-linux-gnu/bin/ -B/usr/local/x86_64-pc-linux-gnu/lib/ -isystem /usr/local/x86_64-pc-linux-gnu/include -isystem /usr/local/x86_64-pc-linux-gnu/sys-include -m32 -DHAVE_CONFIG_H -I. -I../../../../gcj/libjava -I./include -I./gcj -I../../../../gcj/libjava -Iinclude -I../../../../gcj/libjava/include -I../../../../gcj/libjava/classpath/include -Iclasspath/include -I../../../../gcj/libjava/classpath/native/fdlibm -I../../../../gcj/libjava/.././libjava/../libgcc -I../../../../gcj/libjava/../zlib -I../../../../gcj/libjava/../libffi/include -I../libffi/include -fno-rtti -fnon-call-exceptions -fdollars-in-identifiers -Wswitch-enum -D_FILE_OFFSET_BITS=64 -ffloat-store -fomit-frame-pointer -Usun -Wextra -Wall -D_GNU_SOURCE -DPREFIX=\"/usr/local\" -DTOOLEXECLIBDIR=\"/usr/local/lib/../lib32\" -DJAVA_HOME=\"/usr/local\" -DBOOT_CLASS_PATH=\"/usr/local/share/java/libgcj-13.0.0.jar\" -DJAVA_EXT_DIRS=\"/usr/local/share/java/ext\" -DGCJ_ENDORSED_DIRS=\"/usr/local/share/java/gcj-endorsed\" -DGCJ_VERSIONED_LIBDIR=\"/usr/local/lib/../lib32/gcj-13.0.0-18\" -DPATH_SEPARATOR=\":\" -DECJ_JAR_FILE=\"\" -DLIBGCJ_DEFAULT_DATABASE=\"/usr/local/lib/../lib32/gcj-13.0.0-18/classmap.db\" -DLIBGCJ_DEFAULT_DATABASE_PATH_TAIL=\"gcj-13.0.0-18/classmap.db\" -fno-omit-frame-pointer -g -O2 -D_GNU_SOURCE -m32 -MT prims.lo -MD -MP -MF .deps/prims.Tpo -c ../../../../gcj/libjava/prims.cc  -fPIC -DPIC -o .libs/prims.o
../../../../gcj/libjava/prims.cc: In function ‘void _Jv_catch_segv(int, siginfo_t*, void*)’:
../../../../gcj/libjava/prims.cc:182:23: internal compiler error: Segmentation fault
  182 |     = new java::lang::NullPointerException;
      |                       ^~~~~~~~~~~~~~~~~~~~
0x119fa6f crash_signal
        ../../gcj/gcc/toplev.cc:322
0x7f792fa09d5f ???
        ./signal/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
0xbb1944 location_wrapper_p(tree_node const*)
        ../../gcj/gcc/tree.h:4210
0xbb1944 tree_strip_any_location_wrapper(tree_node*)
        ../../gcj/gcc/tree.h:4222
0xbb1944 is_overloaded_fn(tree_node*)
        ../../gcj/gcc/cp/tree.cc:2565
0xbb1c88 really_overloaded_fn(tree_node*)
        ../../gcj/gcc/cp/tree.cc:2607
0xa4b1f0 build_new_1
        ../../gcj/gcc/cp/init.cc:3343
0xa4d748 build_new(unsigned int, vec<tree_node*, va_gc, vl_embed>**, tree_node*, tree_node*, vec<tree_node*, va_gc, vl_embed>**, int, int)
        ../../gcj/gcc/cp/init.cc:4068
0xb03ff7 cp_parser_new_expression
        ../../gcj/gcc/cp/parser.cc:9307
0xb04663 cp_parser_unary_expression
        ../../gcj/gcc/cp/parser.cc:8895
0xad43ea cp_parser_binary_expression
        ../../gcj/gcc/cp/parser.cc:10044
0xad4d1e cp_parser_assignment_expression
        ../../gcj/gcc/cp/parser.cc:10349
0xad7575 cp_parser_constant_expression
        ../../gcj/gcc/cp/parser.cc:10650
0xad76a1 cp_parser_initializer_clause
        ../../gcj/gcc/cp/parser.cc:25342
0xadac1c cp_parser_initializer
        ../../gcj/gcc/cp/parser.cc:25280
0xb0a033 cp_parser_init_declarator
        ../../gcj/gcc/cp/parser.cc:22844
0xae4edb cp_parser_simple_declaration
        ../../gcj/gcc/cp/parser.cc:15315
0xae6caa cp_parser_declaration_statement
        ../../gcj/gcc/cp/parser.cc:14394
0xae7448 cp_parser_statement
        ../../gcj/gcc/cp/parser.cc:12471
0xae827d cp_parser_statement_seq_opt
        ../../gcj/gcc/cp/parser.cc:12883
Please submit a full bug report, with preprocessed source (by using -freport-bug).
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
make[5]: *** [Makefile:9937: prims.lo] Error 1
make[5]: Leaving directory '/home/zopolis4/burngnu/x86_64-pc-linux-gnu/32/libjava'
make[4]: *** [Makefile:10250: all-recursive] Error 1
make[4]: Leaving directory '/home/zopolis4/burngnu/x86_64-pc-linux-gnu/32/libjava'
make[3]: *** [Makefile:12784: multi-do] Error 1
make[3]: Leaving directory '/home/zopolis4/burngnu/x86_64-pc-linux-gnu/libjava'
make[2]: *** [Makefile:12750: all-multi] Error 2
make[2]: Leaving directory '/home/zopolis4/burngnu/x86_64-pc-linux-gnu/libjava'
make[1]: *** [Makefile:15741: all-target-libjava] Error 2
make[1]: Leaving directory '/home/zopolis4/burngnu'
make: *** [Makefile:1026: all] Error 2
```
Similar errors will appear with `make -k`. I am unaware of the exact area of code that is causing the error, although I believe it has something to do with the allocation of CNI classes.  Discussion of this issue on the gcc mailing lists can be found [here](https://gcc.gnu.org/pipermail/gcc-help/2022-May/141597.html). I have tried to find the issue by bisecting, attempts at which can be found on the `grebase1` and `grebase2` branches, but have since lost momentum.

**Comment by abcpro1** [comment] 2022-07-09 11:39
Hello @Zopolis4. Are you still interested in closing this issue?

**Comment by Zopolis4** [comment] 2022-07-10 10:31
> Hello @Zopolis4. Are you still interested in closing this issue?

Yes, very much so.

**Comment by abcpro1** [comment] 2022-07-10 18:55
OK. Is this issue about solving this specific ICE only, or is it about making the compiler compile and work? Because after solving this particular ICE there may be other compilation errors.

**Comment by Zopolis4** [comment] 2022-07-10 22:06
> OK. Is this issue about solving this specific ICE only, or is it about making the compiler compile and work? Because after solving this particular ICE there may be other compilation errors.

The bounty and this issue are just about solving the ICE's. After this particular ICE there are several more of the same type and I am highly confident that they will be solved by the fix for the first. After those, there are a couple more errors which I can deal with myself.

**Comment by abcpro1** [comment] 2022-07-11 13:42
Fair enough.

**Comment by abcpro1** [comment] 2022-07-11 14:56
Here is a pull request #3 fixing the ICE with an explanation of the cause.

**Comment by Zopolis4** [comment] 2022-07-13 09:12
Thanks!

**Closed** 2022-07-13 09:12 UTC
